var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                             *                                                  ",
   "          b                  *                     b              b             ",
   "        xxxxx              xxxxx                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                 xxx      o         o o      xx                                 ",
   "                          o                            **        xx!xx          ",
   "                       xxxxxx      xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                                                                          x  ",
   "  x                                      xxxxx                             o x  ",
   "  x                   x  o                                                   x  ",
   "  x  @              x       x x                **                xxxxx       x  ",
   "  xxxxxxxxxxxx**xxxxxxxxxxxxxxx   xxxxxxxx  xxxxxxxxxx     xxxxxx   xxxxxxxxx   ",
   "              xx              x   x      xb x        x      x                   ",
   "                              x!!!x      xxxx        x!!!!!!x                   ",
   "                              x!!!x                  x!!!!!!x                   ",
   "                              xxxxx                  xxxxxxxx                   ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             *!x  ",
   "                                                                                                             x!x  ",
   "                                                              xx           xx                                x!x  ",
   "                                                x!!x                                                         x!x  ",
   "                                                x!!x                         v                    o   o   o  x!x  ",
   "                                                xx!x              b   o                                     xx!x  ",
   "                                                 x!x                                          xxxxxx xxx xxxx!!x  ",
   "                                                 xvx               x   x                       x!!!!!!!!!!!!!!xx  ",
   "                                                                 |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                        xxx xxxx!!!!!!!!!!!xx           x                         ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                         xx    x     x   x         xxxxxxx            xxx     xxx                 ",
   "                                               x     x    xx                                   x x                ",
   "                                              xx     x       xx                             xxxx                  ",
   "                                          o    xxxxxxx    xxx                                  x                  ",
   "                                         xxx   x     x                             xxxxx     x                    ",
   "                                            b xx     x      o  o     x   x                   x                    ",
   "                 xxx           xxx           x  x     x              x   x                 xxx                    ",
   "                            xx  x   x  xxx     x     x     xxxxxx    x      xxxxxxxxx       x                     ",
   "             xxx     xx         x   x          x     x               x   x    x               x                   ",
   "     @       x!!!!!!!!!x        x   x          x     xxxx            x   x   x            xxxx                    ",
   "    xxx      x!!!!!!!!!x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx***xx         x     x               x     b     x x !!!!!!!!x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!!!!!x     =     x x !!!!!!!!x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xxxxxxxxxxxxxxxxxxxxx                                ",
   "!!!!x x!!!!!!x         x!!!!!x                                                                                    ",
   "!!!!x x!!!!!!x         x!!!!!x                                                                                    ",
   "                                                                                                                  "],
  ["                                  v          v                                                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      b                                                       ",
   "                                      x * x           x              x                 x!!!x                  ",
   "                    v        xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x      xxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx  xx                                     xxx                      ",
   "  xxx                         x     x            xxxx                               x!!!x                xxx  ",
   "  x x                         x    xxx                                                v                  x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x       x   xx   x                          b   x                        o   x  ",
   "  x                           xx          x                              x x x                       xxx   x  ",
   "  x                                      xx       |xxxx|    |xxxx|     xxx xxx                     x       x  ",
   "  x                                o o    x                              x                        x        x  ",
   "  x                 xxxx     xxx          *                             xxx                      x         x  ",
   "  x              xx!!!!!!!!!!!x    xxx    *                             x!                      xxx        x  ",
   "  x            xxxxxxxxxxxxxxxxxxxxxxxxxxxx  x oo x    x oo x    x oo  xx!!                     xxx        x  ",
   "  x      @    x               x           x!!x    x!!!!x    x!!!!x    xx!!!           b           x   ***  x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                      o      b          o             x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                                                                   ",
   "       x     x                                                  x x   x x   x x   x x   x x  *x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                    b                                                                            ",
   "  x         x o xxxxxxxxx o xxxxxxxxx * xx                                          *     x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx       *                                                             ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
   ["                                 ",
    "           x    x                ",  
    "           x    x                ",    
    "           x    x                ",
    "            xxxx                 ",
    "                                 ", 
    " x         x   x   x     x  x    ",
    "  x   x   x    x   x x   x  x    ",
    "   x x x x     x   x   x x       ",
    "    x   x      x   x    xx  x    "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
